name: Set up

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
              python-version: "3.11"
              cache: poetry
        - name: Install Poetry
          run: pip install poetry
          shell: bash
        - name: Install dependencies
          run: poetry install
          shell: bash
