name: Set up
description: Set up Python and Poetry

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        id: cached-pip
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Poetry
      if: steps.cached-pip.outputs.cache-hit != "true"
      run: pip install poetry
      shell: bash
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: poetry
    - name: Install dependencies
      run: poetry install
      shell: bash
