name: CI
on:
    push:
    pull_request:
        branches: main

jobs:
    setup:
      uses: ./.github/workflows/setup.yml

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Run tests
              run: poetry run coverage run --branch -m pytest
            - name: Coverage report
              run: poetry run coverage xml
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
